### ISSUE TITLE
How to upgrade to a new version of shadow-cljs

### ISSUE THREAD

**Issue by kkinnear** [thheller/zprint-npm#1]
Thank you (again) for jumping in and doing this repo.  I have cloned it and I use it to test that zprint will work with shadow-cljs before I release new versions of zprint.

When I cloned this, it used shadow-cljs 2.0.132, from what I can tell.  At some point, I managed to get the version of shadow-cljs upgraded to 2.8.62.  At least that is what I've been running:

```
Kims-MacBook-Air:zprint-npm kkinnear$ shadow-cljs info
shadow-cljs - config: /Users/kkinnear/homeroot/kkinnear/clojure/clone/zprint-npm/shadow-cljs.edn  cli version: 2.8.62  node: v13.11.0
=== Version
jar:            2.8.62
cli:            2.8.62
deps:           1.3.1
config-version: 2.8.62
```
Now I want to upgrade to 2.8.93, but I can't figure out how to do it.  I've changed the only place I could find 2.8.62 in any file (`package.json`), but that didn't do anything.  My notes just say "Update shadow-cljs to 2.8.62", and don't mention how I did this before.

I expect that there is something simple that I'm missing.  Sorry to bother you with this, particularly since I obviously did this before with no problem, but I'm stuck.  

Thanks!

**Comment by thheller** [comment]
You just edit `package.json` and add the version you want and then run `npm install` to get it.

**Comment by kkinnear** [comment]
Thank you so much.  I was missing the `npm install shadow-cljs` part.  Thanks again!
